### ISSUE TITLE
This module does not work; please deprecate

### ISSUE THREAD

**Issue by summivox** [tunnckoCore/manage-arguments#1]
See https://gist.github.com/summivox/47cfa0947e855995c002  for proof.

**Comment by creynders** [comment]
Indeed. 

> The arguments object must not be passed or leaked anywhere.

But since you can't use this w/o passing an arguments object to it your function will still be deoptimised. There's no other run-time solution except copying them one-by-one to an array

**Comment by tunnckoCore** [comment]
I can't get it. This package just do what Petka suggests to be done. Code is directly from his article.

**Comment by tunnckoCore** [comment]
Got it, but anyway. I use `sliced`.
